### ISSUE TITLE
im kindo f an idiot

### ISSUE THREAD

**Issue by Hankypoo7** [peter-marshall5/thisissand-hack#2]
how the hell do i use this

**Comment by peter-marshall5** [comment]
You will need to have the Rust development toolchain installed. Use `cargo run` to compile and run it.

I know that that's way too complicated for most people, so I'm working on a TamperMonkey version. It will probably be released within the next hour or so.

**Comment by peter-marshall5** [comment]
[Here it is!](https://greasyfork.org/en/scripts/461389-thisissand-image-hack) I also added a note to the README section about it.
